upload:
  local_file: data/housing.csv
  bucket: nw-yanmengsong-s3
  s3_file: housing.csv

import:
  s3_file: housing.csv
  bucket: nw-yanmengsong-s3
  local_file: data/housing_raw.csv

clean:
  cols_to_drop: [id, url, region_url, image_url, description]
  cols_to_use: [price, type, sqfeet, beds, baths, smoking_allowed, dogs_allowed,
                wheelchair_access, comes_furnished, laundry_options, state, region]

train:
  label: price
  split_data:
    test_size: 0.25
    random_state: 42
  best_params:
    n_estimators: 300
    random_state: 1
  save_tmo_path: model/model.pkl

evaluate:
  label: price
  split_data:
    test_size: 0.25
    random_state: 42
  save_tmo_path: model/model.pkl
  save_res_path: model/result.csv

