import:
  bucket: nw-yanmengsong-s3
  s3_file: housing.csv

clean:
  cols_to_drop: [id, url, region_url, image_url, description]
  cols_to_use: [price, type, sqfeet, beds, baths, smoking_allowed, dogs_allowed,
                wheelchair_access, comes_furnished, laundry_options, state, region]

featurize:
  categorical_cols: [type, laundry_options, state]

train:
  label: price
  split_data:
    test_size: 0.25
    random_state: 42
  best_params:
    n_estimators: 100
    random_state: 1

score:
  label: price

evaluate:
  label: price
  metrics: [rmse]


